#!/bin/sh
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 OpenFollow Project
#
# Reference the root and boot filesystems by UUID instead of the image
# layout's default /dev/disk/by-slot/* symlinks. Those symlinks are created by
# an RPI_ONBOOTDEV-gated udev rule that has to resolve inside the initramfs
# before the root mounts; when it does not (Pi 5), rootwait blocks and boot
# drops to the initramfs rescue shell. UUID references ride the stock
# /dev/disk/by-uuid links (no boot-device gate), so initramfs-tools resolves
# them reliably, and a UUID is identical across boot media (SD / eMMC / NVMe).
#
# Runs as a genimage exec-pre step, chained after the image layout's own
# setup.sh (wired by pre-image.sh). Args: <LABEL> [IMAGE_OUTPUTDIR]
#   BOOT -> rewrite root= in cmdline.txt on the boot partition
#   ROOT -> rewrite the two by-slot entries in /etc/fstab on the root partition
set -eu

LABEL="${1:?usage: openfollow-root-ref.sh BOOT|ROOT [outputdir]}"
OUTDIR="${2:-${IGconf_image_outputdir:?image outputdir not provided}}"

# ROOT_UUID (full UUID) and BOOT_UUID (vfat XXXX-XXXX) are generated by the
# build and fed to mke2fs/mkdosfs; reuse the exact same values.
. "$OUTDIR/img_uuids"
: "${ROOT_UUID:?missing ROOT_UUID}" "${BOOT_UUID:?missing BOOT_UUID}"
: "${IMAGEMOUNTPATH:?genimage mount path not set}"

# In-place edit via a temp file, portable across GNU and BSD sed (no -i).
# Write the result back over the original file rather than mv'ing the temp
# into place, so the file keeps its existing mode and owner (a mv would give
# /etc/fstab the temp file's 0600 instead of the expected 0644).
edit() {
   _f="$1"
   shift
   _t=$(mktemp)
   sed "$@" "$_f" >"$_t"
   cat "$_t" >"$_f"
   rm -f "$_t"
}

case "$LABEL" in
   BOOT)
      f="$IMAGEMOUNTPATH/cmdline.txt"
      edit "$f" -e "s|root=/dev/disk/by-slot/system|root=UUID=$ROOT_UUID|"
      if grep -q "by-slot" "$f"; then
         echo "openfollow-root-ref: by-slot root ref survived in cmdline.txt" >&2
         exit 1
      fi
      ;;
   ROOT)
      f="$IMAGEMOUNTPATH/etc/fstab"
      edit "$f" \
         -e "s|^/dev/disk/by-slot/system[[:space:]]|UUID=$ROOT_UUID |" \
         -e "s|^/dev/disk/by-slot/boot[[:space:]]|UUID=$BOOT_UUID |"
      if grep -q "by-slot" "$f"; then
         echo "openfollow-root-ref: by-slot ref survived in fstab" >&2
         exit 1
      fi
      ;;
   *)
      echo "openfollow-root-ref: unknown label '$LABEL'" >&2
      exit 1
      ;;
esac
